apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: httpbin-3
  labels:
    app: httpbin-3
    test: tracing
  annotations:
    k8s.v1.cni.cncf.io/networks: test/blue
    tracing.k8s.io/traceparent: "00-c0256a1f41affd828f4eb26caea0c6d1-bfedc8033cf87a16-01"
spec:
  containers:
  - name: httpbin
    image: localhost:5000/go-httpbin:2.20
    command:
    - /bin/go-httpbin
    args:
    - -port=8080
    ports:
    - containerPort: 8080
